#!/usr/bin/env bash
# Provision a REAL Tailnet enrollment bundle via the pinned Go encoder.
#
# The one-time auth key is read from $P0T_AUTH_KEY (never written to disk,
# never printed, never committed). The control URL comes from $P0T_CONTROL_URL.
# Output: $P0T_TMP/offline.bundle pushed to $P0T_DEVICE_DIR/offline.bundle with
# on-device digest verified. A REDACTED description is emitted for evidence.
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

CONTROL_URL="${P0T_CONTROL_URL:-https://controlplane.tailscale.com}"
AUTH_KEY="${P0T_AUTH_KEY:-}"
[[ -n "$AUTH_KEY" ]] || { echo "P0T_AUTH_KEY is empty" >&2; exit 1; }

now="$(date +%s)"
expiry="$((now + 86400))"
b64url32() {
  python3 - "$1" <<'PY'
import hashlib, base64, sys
print(base64.urlsafe_b64encode(hashlib.sha256(sys.argv[1].encode()).digest()).rstrip(b'=').decode())
PY
}
APP_KEY_FP="$(b64url32 app-key-fp)"
TICKET_DIGEST="$(b64url32 ticket-digest)"
POLICY_DIGEST="$(b64url32 policy-digest)"

json_desc="$(python3 - "$CONTROL_URL" "$expiry" "$APP_KEY_FP" "$TICKET_DIGEST" "$POLICY_DIGEST" <<'PY'
import json, sys
control_url, expiry, fp, ticket, policy = sys.argv[1:]
print(json.dumps({
  "hostname": "p0t-offline-device",
  "controlUrl": control_url,
  "pinnedIpv4": "100.96.0.1",
  "pinnedIpv6": "",
  "magicDns": "p0t-bridge.invalid",
  "appKeyFingerprint": fp,
  "ticketDigest": ticket,
  "policyDigest": policy,
  "deviceId": "p0t-offline-device-1",
  "generation": 7,
  "policyRevision": 2,
  "expiryEpochSeconds": int(expiry),
}, separators=(",", ":")))
PY
)"

staged_source="$P0T_TOOLCHAINS/tsnet-src-v1.98.10"
build_root="$P0T_TMP/provision-build"
rm -rf "$build_root"; mkdir -p "$build_root/tsnetbridge"
(cd "$P0T_WRAPPER" && find . -name '*.go' -print0 | tar --null -cf - -T -) | tar -xf - -C "$build_root/tsnetbridge"
python3 - "$P0T_WRAPPER/go.mod.template" "$staged_source" "$build_root/go.mod" <<'PY' >/dev/null
import pathlib, sys
src = pathlib.Path(sys.argv[1]).read_text()
staged = pathlib.Path(sys.argv[2]).resolve()
out = []
for line in src.splitlines():
    out.append(f'replace tailscale.com => {staged}' if line.startswith('replace tailscale.com') else line)
pathlib.Path(sys.argv[3]).write_text('\n'.join(out) + '\n')
PY
cp "$P0T_WRAPPER/go.sum" "$build_root/go.sum"

export PATH='/usr/sbin:/usr/bin:/bin'
export HOME="$P0T_TOOLCHAINS/tsnet-home"
export TMPDIR="$P0T_TOOLCHAINS/tsnet-tmp"
export GOMODCACHE="$P0T_TOOLCHAINS/gomodcache"
export GOPROXY="file://$P0T_TOOLCHAINS/gomodcache/cache/download"
export GOSUMDB='off'
export GOTOOLCHAIN='local'
export GOCACHE="$P0T_TOOLCHAINS/go-build-cache"
export CGO_ENABLED='0'
export TZ='UTC'
export LC_ALL='C.UTF-8'
mkdir -p "$HOME" "$TMPDIR"

# auth key only flows through the pipeline to the Go encoder's stdin.
set +e
python3 - "$json_desc" "$AUTH_KEY" <<'PY' | (cd "$build_root" && /usr/sbin/go run ./tsnetbridge/cmd/enrollment-bundle) >"$P0T_TMP/offline.bundle" 2>"$P0T_TMP/offline-provision.err"
import struct, sys
for payload in sys.argv[1:]:
    b = payload.encode()
    sys.stdout.buffer.write(struct.pack('>I', len(b)))
    sys.stdout.buffer.write(b)
PY
enroll_status="${PIPESTATUS[1]}"
set -e
if [[ "$enroll_status" -ne 0 ]]; then
  echo "ENROLL_PROVISION_FAILED" >&2; cat "$P0T_TMP/offline-provision.err" >&2; exit 1
fi
sha256sum "$P0T_TMP/offline.bundle" | awk '{print $1}' >"$P0T_TMP/offline.bundle.sha256"
echo "BUNDLE_GENERATED bytes=$(wc -c <"$P0T_TMP/offline.bundle") sha256=$(cat "$P0T_TMP/offline.bundle.sha256")"

adb_dev shell mkdir -p "$P0T_DEVICE_DIR"
adb_dev push "$P0T_TMP/offline.bundle" "$P0T_DEVICE_DIR/offline.bundle" >/dev/null
dev_sha="$(adb_dev shell "sha1sum $P0T_DEVICE_DIR/offline.bundle" 2>/dev/null | awk '{print $1}' | tr -d '\r')"
echo "BUNDLE_PUSHED device=$P0T_DEVICE_DIR/offline.bundle device_sha256=$dev_sha"
host_sha1="$(sha1sum "$P0T_TMP/offline.bundle" | awk '{print $1}')"
[[ -n "$dev_sha" && "$dev_sha" == "$host_sha1" ]] && echo "ENROLL_BUNDLE_READY"
