#!/usr/bin/env bash
# Generate the authoritative fail-closed ALTSNET1 bundle with the pinned Go
# `cmd/enrollment-bundle` encoder, push it to the connected device and verify
# the on-device digest.
#
# The provisioning record is intentionally non-secret and non-routable:
#   controlUrl=https://127.0.0.1  (loopback: no real controller, fail closed)
#   dummy auth key (never a tskey-* value)
# Expiry is set to now + 3600 so decode rejects nothing pre-run.
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

now="$(date +%s)"
expiry="$((now + 86400))"

b64url32() { # deterministic canonical base64url of sha256(label)
  python3 - "$1" <<'PY'
import hashlib, base64, sys
print(base64.urlsafe_b64encode(hashlib.sha256(sys.argv[1].encode()).digest()).rstrip(b'=').decode())
PY
}

json_desc="$(python3 - "$expiry" "$(b64url32 app-key-fp)" "$(b64url32 ticket-digest)" "$(b64url32 policy-digest)" <<'PY'
import json, sys
expiry, fp, ticket, policy = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
desc = {
  "hostname": "p0t-device-failclosed",
  "controlUrl": "https://127.0.0.1",
  "pinnedIpv4": "100.101.102.103",
  "pinnedIpv6": "",
  "magicDns": "p0t-bridge.invalid",
  "appKeyFingerprint": fp,
  "ticketDigest": ticket,
  "policyDigest": policy,
  "deviceId": "p0t-failclosed-device-1",
  "generation": 7,
  "policyRevision": 2,
  "expiryEpochSeconds": int(expiry),
}
print(json.dumps(desc, separators=(",", ":")))
PY
)"
auth_key="p0t-failclosed-dummy-auth-key-not-a-secret"

# Render a fresh tuple like run-tsnet-go-tests.sh: module root at build_root,
# wrapper package under tsnetbridge/.
staged_source="$P0T_TOOLCHAINS/tsnet-src-v1.98.10"
build_root="$P0T_TMP/provision-build"
rm -rf "$build_root"; mkdir -p "$build_root/tsnetbridge"
(cd "$P0T_WRAPPER" && find . -name '*.go' -print0 | tar --null -cf - -T -) | tar -xf - -C "$build_root/tsnetbridge"
python3 - "$P0T_WRAPPER/go.mod.template" "$staged_source" "$build_root/go.mod" <<'PY' >/dev/null
import pathlib, sys
src = pathlib.Path(sys.argv[1]).read_text()
staged = pathlib.Path(sys.argv[2]).resolve()
out = []
for line in src.splitlines():
    out.append(f'replace tailscale.com => {staged}' if line.startswith('replace tailscale.com') else line)
pathlib.Path(sys.argv[3]).write_text('\n'.join(out) + '\n')
PY
cp "$P0T_WRAPPER/go.sum" "$build_root/go.sum"

export PATH='/usr/sbin:/usr/bin:/bin'
export HOME="$P0T_TOOLCHAINS/tsnet-home"
export TMPDIR="$P0T_TOOLCHAINS/tsnet-tmp"
export GOMODCACHE="$P0T_TOOLCHAINS/gomodcache"
export GOPROXY="file://$P0T_TOOLCHAINS/gomodcache/cache/download"
export GOSUMDB='off'
export GOTOOLCHAIN='local'
export GOCACHE="$P0T_TOOLCHAINS/go-build-cache"
export CGO_ENABLED='0'
export TZ='UTC'
export LC_ALL='C.UTF-8'
export LANG='C.UTF-8'
mkdir -p "$HOME" "$TMPDIR"

# Frame two length-delimited records (JSON description, auth key) per the CLI contract.
python3 - "$json_desc" "$auth_key" >"$P0T_TMP/failclosed.in" <<'PY'
import struct, sys
for payload in sys.argv[1:]:
    b = payload.encode()
    sys.stdout.buffer.write(struct.pack('>I', len(b)))
    sys.stdout.buffer.write(b)
PY
(cd "$build_root" && /usr/sbin/go run ./tsnetbridge/cmd/enrollment-bundle <"$P0T_TMP/failclosed.in" >"$P0T_TMP/failclosed.bundle") 2>"$P0T_TMP/provision.err" || {
  echo "PROVISION_FAILED" >&2; cat "$P0T_TMP/provision.err" >&2; exit 1
}
sha256sum "$P0T_TMP/failclosed.bundle" | awk '{print $1}' >"$P0T_TMP/failclosed.bundle.sha256"
host_sha="$(cat "$P0T_TMP/failclosed.bundle.sha256")"
echo "BUNDLE_GENERATED bytes=$(wc -c <"$P0T_TMP/failclosed.bundle") sha256=$host_sha"

adb_dev shell mkdir -p "$P0T_DEVICE_DIR"
adb_dev push "$P0T_TMP/failclosed.bundle" "$P0T_BUNDLE_REMOTE" >/dev/null
device_sha1="$(adb_dev shell sha1sum "$P0T_BUNDLE_REMOTE" | awk '{print $1}')"
echo "BUNDLE_PUSHED device_path=$P0T_BUNDLE_REMOTE device_sha1=$device_sha1"
[[ -n "$device_sha1" ]] && echo "P0T_FAIL_CLOSED_BUNDLE_READY"
