package com.agentlife.tailnet.core

import androidx.test.ext.junit.runners.AndroidJUnit4
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import tsnetbridge.StateSink
import tsnetbridge.Tsnetbridge

/**
 * "无 Tailnet 时 fail closed（不 fallback 公共网络）" on a real device:
 *
 * 1. No enrollment source at all   -> the core refuses to start, nothing persisted.
 * 2. Malformed provisioning bundle -> the native seam rejects with INVALID_BUNDLE.
 * 3. Reachable loopback but no controller (127.0.0.1:443, generated by the
 *    authoritative pinned Go encoder and pushed host-side) -> native start
 *    fails with CONTROL_UNREACHABLE; no node state is persisted; and in every
 *    case the system VPN network-agent count is unchanged (no VPN slot grab,
 *    no public-network fallback tunnel).
 */
@RunWith(AndroidJUnit4::class)
class P0tFailClosedEnrollmentInstrumentedTest {

    @Test
    fun unavailableEnrollmentSourceFailsClosedWithoutVpnOrState() {
        val before = P0tVpnAudit.vpnNetworkCount()
        val store = NoBackupTailnetStateStore(InMemoryEncryptedNoBackupState())
        val core = AndroidTsnetBinding(UnavailableNativeEnrollmentSource)

        val failure = runSuspendCatching { core.start("p0t-device-fail", store) }

        assertNotNull("unavailable enrollment must fail closed", failure)
        assertTrue(failure!!.message?.contains("unavailable") == true)
        assertNull("failure must not persist node state", store.restoreNodeState())
        assertEquals("failure must not create a VPN network agent", before, P0tVpnAudit.vpnNetworkCount())
    }

    @Test
    fun malformedBundleIsRejectedByNativeSeamWithoutVpn() {
        val before = P0tVpnAudit.vpnNetworkCount()
        val junk = ByteArray(16) { 0x5A } // invalid ALTSNET1 magic -> INVALID_BUNDLE
        val failure = runCatching {
            Tsnetbridge.start(junk, ByteArray(0), sink)
        }.exceptionOrNull()

        assertNotNull("malformed enrollment must be rejected", failure)
        assertTrue("expected INVALID_BUNDLE, got ${failure!!.message}", failure.message?.startsWith("INVALID_BUNDLE") == true)
        assertEquals("rejection must not create a VPN network agent", before, P0tVpnAudit.vpnNetworkCount())
    }

    @Test(timeout = 150_000)
    fun unreachableControlFailsClosedWithoutVpnOrPublicFallback() {
        val bundle: ByteArray = requireNotNull(
            P0tProvisioning.failClosedBundleBytes(),
        ) { "p0tFailClosedBundle provisioning blob missing; run " +
            "apps/android/tailnet-core/tools/p0t-device/provision-failclosed-bundle.sh " +
            "before this connected run" }
        val before = P0tVpnAudit.vpnNetworkCount()
        val store = NoBackupTailnetStateStore(InMemoryEncryptedNoBackupState())
        val core = AndroidTsnetBinding(object : NativeEnrollmentSource {
            override fun bootstrapBytes(): ByteArray = bundle.copyOf()
        })

        val failure = runSuspendCatching { core.start("p0t-device-failclosed", store) }

        assertNotNull("unreachable control must fail closed", failure)
        assertTrue(
            "expected CONTROL_UNREACHABLE, got ${failure!!.message}",
            failure.message?.startsWith("CONTROL_UNREACHABLE") == true,
        )
        assertNull("control failure must not persist node state", store.restoreNodeState())
        assertEquals(
            "fail-closed must not create a VPN network agent",
            before,
            P0tVpnAudit.vpnNetworkCount(),
        )
    }

    private fun runSuspendCatching(block: suspend () -> Unit): Throwable? {
        var caught: Throwable? = null
        runSuspend {
            caught = runCatching { block() }.exceptionOrNull()
        }
        return caught
    }

    private val sink = object : StateSink {
        override fun persistState(state: ByteArray) {
            // Surface probe only: a real node state is never produced because
            // every enrollment path above is expected to fail closed.
        }
    }
}
