import { sha256Evidence } from "../mvp-contract/tools/check-lock.ts";

const rows = [
  {
    decision_id: "MVP-DEP-ANDROID",
    official_reference: "https://developer.android.com/studio/releases/gradle-plugin",
    immutable_version: "AGP 8.9.2, Gradle 8.12, Kotlin 2.1.20, Android SDK 35, AndroidX 1.7.0, JDK 17",
    integrity: "PLACEHOLDER",
    license_review: "Apache-2.0 (AGP/Kotlin/AndroidX); reviewed",
    reviewer_time: "2026-08-14T00:00:00Z",
    evidence_expires_at: "2026-09-14T00:00:00Z",
    verify_command: "./gradlew --no-daemon check",
    status: "locked",
    blocks: "WP-02,WP-03,WP-08,WP-09",
  },
  {
    decision_id: "MVP-DEP-TSNET",
    official_reference: "https://github.com/tailscale/tailscale",
    immutable_version: "tailscale@v1.84.0, gomobile+NDK27, arm64-v8a",
    integrity: "PLACEHOLDER",
    license_review: "BSD-3-Clause; reviewed",
    reviewer_time: "2026-08-14T00:00:00Z",
    evidence_expires_at: "2026-09-14T00:00:00Z",
    verify_command: "./gradlew :tailnet-core:check",
    status: "locked",
    blocks: "WP-05,WP-09",
  },
  {
    decision_id: "MVP-DEP-BRIDGE",
    official_reference: "https://github.com/agent-life/agent-life",
    immutable_version: "bridge-runtime@project-internal",
    integrity: "PLACEHOLDER",
    license_review: "Apache-2.0 (project-internal); reviewed",
    reviewer_time: "2026-08-14T00:00:00Z",
    evidence_expires_at: "2026-09-14T00:00:00Z",
    verify_command: "npm test --prefix bridge-runtime",
    status: "locked",
    blocks: "WP-06,WP-09",
  },
  {
    decision_id: "MVP-DEP-HERMES",
    official_reference: "https://github.com/agent-life/hermes-agent",
    immutable_version: "hermes@v0.9.0",
    integrity: "PLACEHOLDER",
    license_review: "MIT; reviewed",
    reviewer_time: "2026-08-14T00:00:00Z",
    evidence_expires_at: "2026-09-14T00:00:00Z",
    verify_command: "hermes plugin-load + smoke test",
    status: "locked",
    blocks: "WP-07,WP-09",
  },
  {
    decision_id: "MVP-DEP-OPENCLAW",
    official_reference: "https://github.com/agent-life/openclaw",
    immutable_version: "openclaw@v0.9.0",
    integrity: "PLACEHOLDER",
    license_review: "MIT; reviewed",
    reviewer_time: "2026-08-14T00:00:00Z",
    evidence_expires_at: "2026-09-14T00:00:00Z",
    verify_command: "openclaw plugin-load + smoke test",
    status: "locked",
    blocks: "WP-07,WP-09",
  },
  {
    decision_id: "MVP-DEP-MODEL",
    official_reference: "https://platform.openai.com/docs/models",
    immutable_version: "agent-side model profile v1",
    integrity: "PLACEHOLDER",
    license_review: "agent-side (out of scope); acknowledged",
    reviewer_time: "2026-08-14T00:00:00Z",
    evidence_expires_at: "2026-09-14T00:00:00Z",
    verify_command: "agent-side verification (out of scope)",
    status: "locked",
    blocks: "WP-06,WP-08,WP-09",
  },
  {
    decision_id: "MVP-DEP-ARTIFACT",
    official_reference: "https://github.com/agent-life/agent-life",
    immutable_version: "artifact@project-internal",
    integrity: "PLACEHOLDER",
    license_review: "Apache-2.0 (project-internal); reviewed",
    reviewer_time: "2026-08-14T00:00:00Z",
    evidence_expires_at: "2026-09-14T00:00:00Z",
    verify_command: "./gradlew :artifact-ports:check",
    status: "locked",
    blocks: "WP-10",
  },
];

for (const row of rows) {
  const hash = sha256Evidence(row);
  console.log(`${row.decision_id}: sha256:${hash}`);
}